import {expect,test} from "bun:test";
import {generateKeyPairSync,sign} from "node:crypto";
import {PublicKey} from "@solana/web3.js";
import {demoHttp} from "../../src/_adapters/_0_solana/_7_demo/_5_http/mod";
import type {DemoRuntime} from "../../src/_adapters/_0_solana/_7_demo/_4_runtime/mod";
test("demo login binds owner, origin and one-use nonce; anonymous mutations rejected",async()=>{
 const key=generateKeyPairSync("ed25519"),owner=new PublicKey(key.publicKey.export({format:"der",type:"spki"}).subarray(-32)).toBase58();
 const runtime={market:{chain:{env:{judge:{owner}}}}} as DemoRuntime;
 const handler=demoHttp(runtime,"http://localhost:3000");
 const request=(path:string,body:object,origin="http://localhost:3000")=>handler(new Request(`http://localhost/tmp/app/api/${path}`,{method:"POST",headers:{origin},body:JSON.stringify(body)}));
 expect((await request("reset",{})).status).toBe(401);
 expect((await handler(new Request("http://localhost/tmp/app/api/reference"))).status).toBe(401);
 expect((await request("challenge",{},"http://evil.invalid")).status).toBe(400);
 const challenge=await (await request("challenge",{})).json();
 const signature=sign(null,Buffer.from(challenge.message),key.privateKey).toString("base64");
 const login=await request("login",{message:challenge.message,signature});expect(login.status).toBe(200);
 const token=(await login.json()).token;expect(token).toMatch(/^[a-f0-9]{64}$/);
 runtime.reset=async()=>{throw new Error("Pending approval; reset is unavailable");};
 const denied=await handler(new Request("http://localhost/tmp/app/api/reset",{method:"POST",headers:{Origin:"http://localhost:3000",Authorization:`Bearer ${token}`},body:"{}"}));
 expect(denied.status).toBe(400);expect((await denied.json()).error).toContain("Pending approval");
 expect((await handler(new Request("http://localhost/tmp/app/api/reference",{headers:{Authorization:`Bearer ${token}`}}))).status).toBe(503);
 expect((await request("login",{message:challenge.message,signature})).status).toBe(400);
 expect((await request("login",{message:"forged",signature})).status).toBe(400);
});
test("public lobby verifies the requested wallet before admission and rejects replay",async()=>{
 const a=generateKeyPairSync("ed25519"),b=generateKeyPairSync("ed25519");
 const address=(k:typeof a)=>new PublicKey(k.publicKey.export({format:"der",type:"spki"}).subarray(-32)).toBase58();
 const admitted:string[]=[];
 const runtime={market:{chain:{env:{judge:{owner:address(a)}}}}} as DemoRuntime;
 const lobby={current:runtime,acquire:async(owner:string)=>{admitted.push(owner);}};
 const handler=demoHttp(runtime,"http://localhost:3000",undefined,lobby as never);
 const post=(path:string,body:object)=>handler(new Request(`http://localhost/tmp/app/api/${path}`,{method:"POST",headers:{Origin:"http://localhost:3000"},body:JSON.stringify(body)}));
 const first=await(await post("challenge",{owner:address(b)})).json();
 expect((await post("login",{message:first.message,signature:sign(null,Buffer.from(first.message),a.privateKey).toString("base64")})).status).toBe(400);
 expect(admitted).toEqual([]);
 const challenge=await(await post("challenge",{owner:address(b)})).json();
 const packet={message:challenge.message,signature:sign(null,Buffer.from(challenge.message),b.privateKey).toString("base64")};
 expect((await post("login",packet)).status).toBe(200);expect(admitted).toEqual([address(b)]);
 expect((await post("login",packet)).status).toBe(400);
 expect((await handler(new Request("http://localhost/tmp/app/api/state"))).status).toBe(401);
});
